---
title: "Using GitHub Actions in R"
author: "Maximilian Held"
date: "`r Sys.Date()`"
output: rmarkdown::html_document
vignette: >
   %\VignetteIndexEntry{Rscript-byod}
   %\VignetteEngine{knitr::rmarkdown}
   %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Why You Should Care



## Actions

The below workflow function(s) paste together individual actions.
There are also separate functions to generate these individual actions, which again, are simple paste jobs.

They only exist as R functions to simplify the documentation in *one* place and to reuse them elegantly across several actions.


```
# just pseudocode, does not exist yet
ghaction::Rsync_byod(
  title = "Render rmarkdown", 
  needs = "Build image", 
  uses = "maxheld83/ghactions/Rscript-byod@master"
  args = "-e 'rmarkdown::render_site()'"
)
```


## Workflows

This function generates `main.workflow` files for common workflow configurations of R projects.

Typical invocations may include:

```r
# this is just pseudcode; functions don't exist yet
ghaction::use_ghaction(type = "rmarkdown", deploy_target = "rsync")
ghaction::use_ghaction(type = "package", covr = TRUE, pkgdown = TRUE, deploy_target = "ghpages")
```




## What This Package *Doesn't* Do

The ghactions package is quite limited, and deliberately so:
GitHub actions already provides most of the things we might want, and in a cross-platform (if somewhat vendor-locked) way:

- a succinct and human-readable text file representation (a subset of the [Hashicorp Configuration Language (HCL)](https://github.com/hashicorp/hcl)) of the [directed acyclic graphs (DAG)](https://en.wikipedia.org/wiki/Directed_acyclic_graph) here used to model code automation workflows,
- a neat graphical user interface that makes to edit your `main.workflow` files in their native graph form,
- a convenient model and marketplace to share actions.

This package does not intend to solve this problem *again*, or to completely wrap GitHub actions in R.
It's really just a glorified collection of templates to get you started quickly.

If you need something more advanced, chances are you're going to want to edit your workflows yourself, using GitHub's native interface.
It's quite easy to use, and I'll try to gather and share best practices in this repository.


## Thanks

ghactions leaves much of the hard work to other open source software and their generous authors.

First and foremost, GitHub Actions is build on top of Docker, and so, by extension, is this package.
It would not work without the tremendous work of [Carl Boettiger](https://www.carlboettiger.info) and [Dirk Edelbuettel](http://dirk.eddelbuettel.com), who carefully maintain versioned Docker images for R through their [Rocker Project](http://rocker-project.org).

This package is also heavily modeled on, and indebted to the [usethis](https://usethis.r-lib.org) package by [Jenny Bryan](https://jennybryan.org) and [Hadley Wickham](http://hadley.nz).


## Related and Prior Work

There are plenty of other proven ways to run CI/CD for R.
Many rely on the [R support on TravisCI](https://docs.travis-ci.com/user/languages/r/), maintained by [Jeron Ooms](https://github.com/jeroen) and [Jim Hester](https://www.jimhester.com).
The [travis](https://ropenscilabs.github.io/travis/) and [tic](https://ropenscilabs.github.io/tic/) packages make it easier to work with them.
You can use [AppVeyor](http://appveyor.com)'s Windows-based system via the [r-appveyor](https://github.com/krlmlr/r-appveyor) package.

For serious, cross-platform testing of packages, there's the [r-hub](http://r-hub.io) project.

There are also other and additional ways to use R and Docker together.
The recommended way to use Dockere here is to simply edit a `DOCKERFILE` by hand, but the [containerit](http://o2r.info/containerit/) package can also, miraculously, do this for you by parsing your project files.
We are here primarily concerned with running R *inside Docker* (inside GitHub actions), but there are also some packages that allow you to control Docker from *inside R*, including [stevedore](https://richfitz.github.io/stevedore/), [harbor](https://github.com/wch/harbor) and [docker](https://bhaskarvk.github.io/docker/)., though it facilitates running Docker *inside R*, whereas GitHub Actions runs R *inside Docker*.
The broader topic of reproducibility in R with the help of Docker is also adressed by the [rrtools](https://github.com/benmarwick/rrtools) and [liftr](https://liftr.me) packages, as well as the [o2r](https://o2r.info) and [ropensci](https://ropensci.org) projects.
