---
title: "Performance"
author: "Maximilian Held"
date: "`r Sys.Date()`"
output: rmarkdown::html_document
vignette: >
   %\VignetteIndexEntry{performance}
   %\VignetteEngine{knitr::rmarkdown}
   %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

For iterating and debugging, CI/CD can never be fast enough.

GitHub actions is still in beta, and performance and features are likely to change.

However, the basic design (consecutive docker image runs along a directed acyclic graph) already implies some conclusions for making the most of the service.


## Caching

There are different levels of caching relevant to the performance of caching.

1. **Build artefacts** are any files created *by* the actions as they run over your repository.
    There is currently *no* native support for caching build artefacts from GitHub actions (tracked in [#48](https://github.com/r-lib/ghactions/issues/48)).
    You *can* persist artefacts *across actions* (anything inside `/github/`), though not *between* workflows or runs.
    
    *ghactions* -- the R package -- currently has its own "McGyvered" caching, using [Google Cloud Storage](https://cloud.google.com/storage/).
    You can look at the `main.workflow` for inspiration, but this likely isn't ready for prime-time yet.
    The preferred solution should be for GitHub actions to support caching natively.
2. **`FROM` image caching** concerns the *downloaded* images from Docker Hub or another registry that are listed in the `FROM` field of the `Dockerfile` driving some action in question.
    Though this isn't documented, GitHub actions appears to be caching those on-site, because even very large images such as `rocker/verse` or `rhub/debian-gcc-release` start running in a matter of seconds (~30).
3. However additional **layers from `RUN`** and similar fields in the `Dockerfile` driving some action appear *not* to be currently cached.
    GitHub's own [actions](https://github.com/actions) appear to all publish their respective images to Docker Hub from where they are apparently pulled and cached *without* running `RUN` and friends again on every action use.
    These images, even with relatively expensive `RUN`s all start running in a matter of seconds (~20).
    The `Dockerfile`s of actions in *ghactions*  are currently all unpublished (tracked in [#141](https://github.com/r-lib/ghactions/issues/141)), and can thus take several minutes (1-5) to spin up.
    Arguably GitHub actions *could* (or did at some point already?) automatically and transparently cache these images (perhaps for published actions?).

To sum up, it appears that:

- Large images are *not* very expensive (though slimming them down is always a good idea, tracked in [#166](https://github.com/r-lib/ghactions/issues/166)).
- `RUN`s and friends *inside* an actions `Dockerfile` are *pretty* expensive.
    Resulting images should be published to a registry for better performance.
- Caching for build artefacts across workflows and runs brings the usual performance gains.
    `remotes::install_deps()` for a medium-sized package such as *ghactions* now completes in around 4 minutes (because of 3 in the above), whereas without caching it took around 15-20 minutes.
    The overhead of the caching actions (un/tarring, down/uploading) is negligible (<20 seconds each).
