FROM maxheld83/base

LABEL "com.github.actions.name"="Document R Packages"
LABEL "com.github.actions.description"="Document Packages for rstats."
LABEL "com.github.actions.icon"="book-open"
LABEL "com.github.actions.color"="blue"

COPY entrypoint.R /entrypoint.R
ENTRYPOINT ["/entrypoint.R"]
