FROM rocker/verse:3.5.2

LABEL "com.github.actions.name"="Run some R"
LABEL "com.github.actions.description"="Run Rscript'"
LABEL "com.github.actions.icon"="terminal"
LABEL "com.github.actions.color"="blue"

LABEL "repository"="http://github.com/maxheld83/ghactions"
LABEL "homepage"="http://www.maxheld.de/ghactions"
LABEL "maintainer"="Maximilian Held <info@maxheld.de>"

ENTRYPOINT ["sh -c 'Rscript'"]
