include ../docker.mk
include ../help.mk
include ../shell.mk

.PHONY: clean
clean: ## Clean up after the build process.

.PHONY: lint
lint: docker-lint

.PHONY: build
build: docker-build ## Build this Action.

.PHONY: test

.PHONY: publish
publish: docker-publish ## Publish this Action.
